version: '3.2'

services:

#-------------------------------------------
# MARIADB
#-------------------------------------------
  mariadb:
    restart: always
    build:
      context: ./docker/mariadb
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MARIADB_DATA_SAVE}:/var/lib/mysql                # volume for data
      - ${MARIADB_LOG_PATH}:/var/log/mysql                 # log mariadb
    environment:
      - MARIADB_VERSION=${MARIADB_VERSION}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}     # root password
      - MARIADB_ROOT_HOST=${MARIADB_ROOT_HOST}             # grant user hostmask (optional)
      - MARIADB_DATABASE=${MARIADB_DATABASE}               # create database (optional)
      - MARIADB_USER=${MARIADB_USER}                       # grant user name (optional)
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}               # grant user password (optional)
    networks:
      - backend

#-------------------------------------------
# NGINX
#-------------------------------------------
  nginx:
    restart: always
    build:
      context: ./docker/nginx
    links:
      - phpfpm-gitscrum
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/default.conf    # config path
      - ${NGINX_LOG_PATH}:/var/log/nginx                       # log nginx
      - ${WWW_DATA}:/var/www/html                              # volume for data
    environment:
      - NGINX_VERSION=${NGINX_VERSION}
    networks:
      - backend

#-------------------------------------------
# PHP-FPM
#-------------------------------------------
  phpfpm-gitscrum:
    restart: always
    build:
      context: ./docker/phpfpm
    links:
      - mariadb     # if you're using mariadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PHPFPM_CONFIG_PATH}:/usr/local/etc/php-fpm.conf                         # config path
      - ${PHPFPM_INI_PATH}:/usr/local/etc/php/php.ini                             # ini path
      - ${PHPFPM_LOG_PATH}:/var/log/phpfpm                                        # log phpfpm
      - ${PHP_XDEBUG_PATH}:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini    # xdebug config
      - ${WWW_DATA}:/var/www/html                                                 # volume for data
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - XDEBUG_VERSION=${XDEBUG_VERSION}
      - DEBUG=1
    networks:
      - backend

#-------------------------------------------
# ADMINER
#-------------------------------------------
  adminer:
    restart: always
    build:
      context: ./docker/adminer
    ports:
      - "${ADMINER_PORT}:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ADMINER_SESSION}:/sessions                    # volume for data
    networks:
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  mariadb:
    driver: "local"
  nginx:
    driver: "local"
  phpfpm-gitscrum:
    driver: "local"
  adminer:
    driver: "local"