version: '3.2'

services:

#-------------------------------------------
# MYSQL
#-------------------------------------------
  mysql:
    restart: always
    build:
      context: ./docker/mysql/${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MYSQL_DATA_SAVE}:/var/lib/mysql                          # volume for data
      - ${MYSQL_LOG_PATH}:/var/log/mysql                           # log mysql
      - ${MYSQL_CONFIG_PATH}:/etc/my.cnf                           # my.cnf mysql
      - ${MYSQL_DOCKER_CONFIG_PATH}:/etc/mysql/conf.d/docker.cnf   # docker.cnf mysql
    environment:
      - MYSQL_VERSION=${MYSQL_VERSION}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}         # root password
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}                 # grant user hostmask (optional)
      - MYSQL_DATABASE=${MYSQL_DATABASE}                   # create database (optional)
      - MYSQL_USER=${MYSQL_USER}                           # grant user name (optional)
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}                   # grant user password (optional)
    networks:
      - backend

#-------------------------------------------
# NGINX
#-------------------------------------------
  nginx:
    restart: always
    build:
      context: ./docker/nginx
    links:
      - phpfpm-gitscrum
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/default.conf    # config path
      - ${NGINX_LOG_PATH}:/var/log/nginx                       # log nginx
      - ${WWW_DATA}:/var/www/html                              # volume for data
    environment:
      - NGINX_VERSION=${NGINX_VERSION}
    networks:
      - backend

#-------------------------------------------
# PHP-FPM
#-------------------------------------------
  phpfpm-gitscrum:
    restart: always
    build:
      context: ./docker/phpfpm
    links:
      - mysql     # if you're using mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PHPFPM_CONFIG_PATH}:/usr/local/etc/php-fpm.conf      # config path
      - ${PHPFPM_INI_PATH}:/usr/local/etc/php/php.ini          # ini path
      - ${PHPFPM_LOG_PATH}:/var/log/phpfpm                     # log phpfpm
      - ${WWW_DATA}:/var/www/html                              # volume for data
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - DEBUG=1
    networks:
      - backend

#-------------------------------------------
# ADMINER
#-------------------------------------------
  adminer:
    restart: always
    build:
      context: ./docker/adminer
    ports:
      - "${ADMINER_PORT}:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ADMINER_SESSION}:/sessions                    # volume for data
    networks:
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  mysql:
    driver: "local"
  nginx:
    driver: "local"
  phpfpm-gitscrum:
    driver: "local"
  adminer:
    driver: "local"